[package]
name = "rusty_vox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
gl_loader = "0.1.2"

[dependencies.glfw]
version = "*"
default-features = true